### ISSUE TITLE
Loading limited rows of data

### ISSUE THREAD

**Issue by masalaman** [mustafaascha/nisr#1]
Any thoughts on how to do it so you only upload a certain number of rows with this wrapper?  My system can't handle the size of these files.

**Comment by mustafaascha** [comment]
You should now be able to use "n_max = 100" to read in only 100 records from the text file. You'll have to reinstall the package for this to work. I haven't tested the feature, yet, so (if you don't mind) let me know how it goes.

**Comment by masalaman** [comment]
Works great thanks so much!
